---

- name: install php requirements
  apt: name="{{item}}"
       state=present
  with_items:
    - php7.2-cli
    - php7.2-common
    - php7.2-fpm
    - php7.2-json
    - php7.2-mysql
    - php7.2-opcache
    - php7.2-readline
  notify:
    - restart php7.2-fpm
