---

- name: install php requirements
  apt: name="{{ item }}"
       state=present
  with_items:
    - php{{ php_fpm_version }}-cli
    - php{{ php_fpm_version }}-common
    - php{{ php_fpm_version }}-fpm
    - php{{ php_fpm_version }}-json
    - php{{ php_fpm_version }}-mysql
    - php{{ php_fpm_version }}-opcache
    - php{{ php_fpm_version }}-readline
  notify:
    - restart php{{ php_fpm_version }}-fpm
