---

- name: Download 3proxy repository
  git:
    repo: "{{ proxy_repo }}"
    dest: "{{ proxy_tmp_path }}"
    version: "{{ proxy_version }}"
    force: yes

- name: Install 3proxy requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make

- name: Compile 3proxy
  shell: "make -f Makefile.Linux"
  args:
    chdir: "{{ proxy_tmp_path }}"

- name: Create directory for 3proxy binary
  file:
    name: "{{ proxy_bin_path }}"
    mode: 0755
    owner: "root"
    group: "root"
    state: directory

- name: Copy 3proxy binary
  copy:
    mode: 0755
    src: "{{ proxy_tmp_path }}/src/3proxy"
    dest: "{{ proxy_bin_path }}/3proxy"
    remote_src: yes

- name: Create 3proxy config
  template:
    mode: 0440
    owner: "root"
    group: "root"
    src: 3proxy.cfg.j2
    dest: "{{ proxy_conf_path }}"

- name: Create systemd unit for 3proxy service
  template:
    src: 3proxy.service.j2
    dest: /etc/systemd/system/3proxy.service

- name: Enable and launch 3proxy service
  systemd:
    name: 3proxy
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Cleanup 3proxy source directory
  file:
    state: absent
    dest: "{{ proxy_tmp_path }}"
    force: yes
