---

- name: install requirements
  apt: name={{item}} state=installed
  with_items:
    - php7.0-cli
    - php7.0-common
    - php7.0-fpm
    - php7.0-json
    - php7.0-mysql
    - php7.0-opcache
    - php7.0-readline
  notify:
    - restart php7.0-fpm
