---

- name: Install nginx
  apt:
    name: nginx
    state: installed

- name: Ensure nginx is running
  service:
    name: nginx
    state: started

- name: Create nginx log dir
  file:
    path: /var/log/nginx/
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Create domain root dir
  file:
    path: {{ domain_rootdir }}
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Generate nginx domain config
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/{{ domain_name }}.conf
    mode: 0644
    owner: root
    group: root

- name: Enable new domain in nginx
  file:
    src: /etc/nginx/sites-available/{{ domain_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ domain_name }}.conf
    state: link
