---

- name: install requirements
  apt: name={{item}} state=present
  with_items:
    - kate
    - okular
    - remmina
    - remmina-common
    - remmina-plugin-rdp
    - remmina-plugin-vnc
    - rdesktop
    - dolphin
    - djvusmooth
    - vlc
    - kvirc
    - gwenview
    - ktorrent
    - kcalc
    - virtualbox
    - virtualbox-dkms
    - firefox
    - google-chrome-stable
    - libreoffice-writer
    - libreoffice-calc
