---

#- name: install python 2
#  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: apt-get update
  apt:
    update_cache: yes

- import_tasks: tools.yml
  tags: tools

- import_tasks: net.yml
  tags: net

#- import_tasks: gui.yml
#  tags: gui
